Updated for mongosh, removed deprecated mongo shell.

diff --git a/src/Reports/Expiration-Report-Gen b/src/Reports/Expiration-Report-Gen
--- a/src/Reports/Expiration-Report-Gen
+++ b/src/Reports/Expiration-Report-Gen
@@ -3,6 +3,9 @@
 # Then mail to the command staff mailing list.
 
 # History:
+# 29Aug23 MEG Upgraded to mongosh, DB passed to script on command line.
+# 17Sep20 MEG Upload files to shared drive, only emails links to mailing list.
+# 17Sep20 MEG Moved all user vars to config file.
 # 06Jul19 MEG Correct sendemail message syntax.
 # 25Nov18 MEG Added options to change mailing list and message.
 # 24Oct18 MEG Added option to skip sending emails.
@@ -10,21 +13,21 @@
 # 01Oct18 MEG Created.
 #
 
-# Message option text or message file template
-MESSAGE="file monthly-expiration-report.html html true"
+# Load config file
+CONF=./$(basename $0).conf
+if [ -f  $CONF ]; then
+    . $CONF
+else
+    echo "Error: missing configuration file: $CONF"
+    exit 1
+fi
 
-WORKDIR=$HOME/work/NHWG/Reports
+# make sure we are standing in the working directory
 cd $WORKDIR
 
-# Report generator MongoDB login credentials
-CREDS=./reporter-creds
-. $CREDS
-
-# target database
-DB=NHWG
-
-# Default mailing list file
-MAILINGLIST=./mailinglist
+# File ID's. Contains the immuteable Google file id for each file uploaded,
+# keyed by the basename of the file from the $REPORTS list
+declare -A FILEID
 
 # cmd line options
 OPTS="h?l:m:n"
@@ -36,40 +39,39 @@ USAGE="Usage: $(basename $0) [$OPTS]\n
 \tm - new message or message file ($MESSAGE)\n
 \tn - No email - skip sending report to mailing list\n
 "
+# Make date stamp
+DATESTAMP=$(date +%Y%m%d)
 
 while getopts $OPTS o; do
     case $o in
-	h|?) echo -e $USAGE;exit 1;;
 	l) MAILINGLIST=OPTARG;;
 	m) MESSAGE=OPTARG;;
 	n) NOEMAIL="true";;
+	h|?) echo -e $USAGE;exit 1;;
 	*) echo -e $USAGE;exit 1;;
     esac
 done
 shift $(($OPTIND - 1))
 
+echo "Preparing expired membership reports"
 
-echo "Preparing expired membership report"
-# Prepare Expired collection for report
-mongo --quiet -u $USERID -p $PASSWD --authenticationDatabase $DB expired.js
-
-# Pull the collected data into a CSV for mailing
-mongoexport --quiet --db $DB -u $USERID -p $PASSWD --authenticationDatabase $DB \
-	    -c Expired --type csv  --sort '{Unit:1,NameLast:1}' \
-	    -f "CAPID,NameLast,NameFirst,Type,Unit,Expiration,EMAIL,HomePhone" >expired-report.csv
-
-# Prepare 30 day outlook expiration report
-echo "Preparing 30 day expiration outlook report"
-mongo --quiet -u $USERID -p $PASSWD --authenticationDatabase $DB Expiring30Days.js >30DayExpiration-Report.csv
-
-# Prepare 60 day outlook expiration report
-echo "Preparing 60 day expiration outlook report"
-mongo --quiet -u $USERID -p $PASSWD --authenticationDatabase $DB Expiring60Days.js >60DayExpiration-Report.csv
+for r in $REPORTS; do
+    echo "Preparing $r report"
+    fn=$DATESTAMP-$r.csv
+    mongosh --quiet -u $USERID -p $PASSWD --authenticationDatabase $DB $DB $r.js >$fn
+# upload the file and save id
+    FILEID[$r]=$(gam user $ASUSER create drivefile \
+		     teamdriveparent "$SHAREDDRIVE" \
+		     teamdriveparentname "$DRIVEFOLDER" \
+		     drivefilename "$fn" localfile "$fn" returnidonly)
+# clean up local file
+    /bin/rm $fn
+done
 
 # If -n switch don't send reports
 [[ -v NOEMAIL ]] && exit 1
 
 echo "Sending reports."
 # Use GAM to email reports to commanders mailing list
-gam sendemail file $MAILINGLIST subject "NHWG:Monthly Expiration Reports" $MESSAGE  attach expired-report.csv attach 30DayExpiration-Report.csv attach 60DayExpiration-Report.csv
+gam sendemail file $MAILINGLIST subject "NHWG:Monthly Expiration Reports" $MESSAGE replace expired ${FILEID[Expired]} replace 30Day ${FILEID[Expiring30Days]} replace 60Day ${FILEID[Expiring60Days]}
 echo Done.
