-L option only installs of gam is not up to date.

diff --git a/src/Utils/gitGAMADVX b/src/Utils/gitGAMADVX
--- a/src/Utils/gitGAMADVX
+++ b/src/Utils/gitGAMADVX
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash -eE
 # Download and install a specified version of GAMADV-XTD3.
 # GAM must have been previous installed and configured with project.
 #
@@ -17,14 +17,19 @@
 ##   limitations under the License.
 
 # History:
-# 15Dec20 MEG added download only option.
-# 15Dec20 MEG exit if archive did not download.
+# 14Jul21 MEG -L now checks for latest, installs if not up to date.
+# 15Dec20 MEG Added download only option.
+# 15Dec20 MEG bail on failed download of archive.
 # 14Dec20 MEG Ross fixed download uri, fixed to track.
 # 14Dec20 MEG Ross changed download uri, fixed to track.
 # 05Dec20 MEG Added install messages.
 # 04Dec20 MEG Find GAMADV latest version for download
 # 26Nov20 MEG Created.
 #
+function die () {
+    echo "ERROR::$0:Download Failed."
+    exit 1
+}
 
 OPTS="Dd:i:l:Lh?u:"
 
@@ -60,13 +65,25 @@ done
 shift $((OPTIND - 1 ))
 
 if [ -v LATEST ]; then
-    GAMVERSION=$(curl -s https://github.com/taers232c/GAMADV-XTD3|egrep ">GAM ([0-9]+\.[0-9]{2}\.[0-9]{2})"|(while read a b c d e f g h i;do echo $h;done)|sed -e 's/<\/span>//')
-elif [ $# = 1 ]; then
-    GAMVERSION=$1
-else
-    echo "Error: no GAM version specified"
-    echo -e $USAGE
-    exit 1
+#    GAMVERSION=$(curl -s https://github.com/taers232c/GAMADV-XTD3|egrep ">GAM ([0-9]+\.[0-9]{2}\.[0-9]{2})"|(while read a b c d e f g h i;do echo $h;done)|sed -e 's/<\/span>//')
+#elif [ $# = 1 ]; then
+#    GAMVERSION=$1
+#else
+#    echo "Error: no GAM version specified"
+#    echo -e $USAGE
+#    exit 1
+#fi
+
+    # Check for latest release, install only if gam not up to date
+    # Depends on Ross's "checkrc" option for the gam version command.
+    # This code replaces the more complex curl call that downloaded
+    # the release page and looks for the latest release version in the page.
+    if gam version checkrc &>/dev/null; then
+	echo "GAM is up to date."
+	exit 0
+    else
+	GAMVERSION=$(gam version checkrc|egrep "^[ \t]+Latest:"|(while read a b;do echo $b;done))
+    fi
 fi
 
 ARCHIVE="gamadv-xtd3-$GAMVERSION-linux-$ARCH-glibc$GLIBCVERSION.tar.xz"
@@ -75,11 +92,11 @@ pushd $DLPATH &>/dev/null
 
 # attempt to download GAM archive
 curl -sL "$GAMURL$GAMVERSION/$ARCHIVE" --output $ARCHIVE
-SIZE=$( wc -c < $ARCHIVE )
-if (( SIZE < 1000000 )); then
-    echo "ERROR:Download failed."
-    exit 1
-fi
+SIZE=$(stat -c%s $ARCHIVE)
+#SIZE=$(wc -c < $ARCHIVE)
+(($SIZE > 2000000)) || die
+#trap "echo ERROR:Download $GAMURL$GAMVERSION/$ARCHIVE failed." ERR
+#wget -q "$GAMURL$GAMVERSION/$ARCHIVE" > $ARCHIVE
 
 # Check for download only
 if [ -v DOWNLOADONLY ]; then
@@ -93,6 +110,7 @@ echo "Installing: $GAMVERSION"
 tar Jxf $ARCHIVE
 
 # you must have access privilege to do the copy to system directories
+# See man setfacl
 cp $DLPATH/gamadv-xtd3/* $INSTALLDIR
 echo "Done."
 
